# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DS_game_start_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_game_start_menu(object):
    def setupUi(self, game_start_menu):
        game_start_menu.setObjectName("game_start_menu")
        game_start_menu.resize(1255, 905)
        self.verticalLayout = QtWidgets.QVBoxLayout(game_start_menu)
        self.verticalLayout.setObjectName("verticalLayout")
        self.decks_gridLayout = QtWidgets.QGridLayout()
        self.decks_gridLayout.setObjectName("decks_gridLayout")
        self.verticalLayout.addLayout(self.decks_gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btn_start = QtWidgets.QPushButton(game_start_menu)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_start.setFont(font)
        self.btn_start.setObjectName("btn_start")
        self.verticalLayout.addWidget(self.btn_start)

        self.retranslateUi(game_start_menu)
        QtCore.QMetaObject.connectSlotsByName(game_start_menu)

    def retranslateUi(self, game_start_menu):
        _translate = QtCore.QCoreApplication.translate
        game_start_menu.setWindowTitle(_translate("game_start_menu", "Dialog"))
        self.btn_start.setText(_translate("game_start_menu", "Начать игру"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    game_start_menu = QtWidgets.QDialog()
    ui = Ui_game_start_menu()
    ui.setupUi(game_start_menu)
    game_start_menu.show()
    sys.exit(app.exec_())
