# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DS_game_start_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_game_start_menu(object):
    def setupUi(self, game_start_menu):
        game_start_menu.setObjectName("game_start_menu")
        game_start_menu.resize(1255, 905)
        self.verticalLayout = QtWidgets.QVBoxLayout(game_start_menu)
        self.verticalLayout.setObjectName("verticalLayout")
        self.deck_name = QtWidgets.QLabel(game_start_menu)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.deck_name.setFont(font)
        self.deck_name.setAlignment(QtCore.Qt.AlignCenter)
        self.deck_name.setObjectName("deck_name")
        self.verticalLayout.addWidget(self.deck_name)
        self.decks_scrollArea = QtWidgets.QScrollArea(game_start_menu)
        self.decks_scrollArea.setWidgetResizable(True)
        self.decks_scrollArea.setObjectName("decks_scrollArea")
        self.decks_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.decks_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1235, 767))
        self.decks_scrollAreaWidgetContents.setObjectName("decks_scrollAreaWidgetContents")
        self.decks_scrollArea.setWidget(self.decks_scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.decks_scrollArea)
        self.btn_start = QtWidgets.QPushButton(game_start_menu)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_start.setFont(font)
        self.btn_start.setObjectName("btn_start")
        self.verticalLayout.addWidget(self.btn_start)

        self.retranslateUi(game_start_menu)
        QtCore.QMetaObject.connectSlotsByName(game_start_menu)

    def retranslateUi(self, game_start_menu):
        _translate = QtCore.QCoreApplication.translate
        game_start_menu.setWindowTitle(_translate("game_start_menu", "Dialog"))
        self.deck_name.setText(_translate("game_start_menu", "Имя колоды"))
        self.btn_start.setText(_translate("game_start_menu", "Начать игру"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    game_start_menu = QtWidgets.QDialog()
    ui = Ui_game_start_menu()
    ui.setupUi(game_start_menu)
    game_start_menu.show()
    sys.exit(app.exec_())
