# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_start.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(722, 666)
        self.verticalWidget = QtWidgets.QWidget(Dialog)
        self.verticalWidget.setGeometry(QtCore.QRect(20, 30, 601, 541))
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Welcome = QtWidgets.QLabel(self.verticalWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Welcome.setFont(font)
        self.Welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.Welcome.setObjectName("Welcome")
        self.verticalLayout.addWidget(self.Welcome)
        self.Explanation = QtWidgets.QLabel(self.verticalWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Explanation.setFont(font)
        self.Explanation.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.Explanation.setWordWrap(True)
        self.Explanation.setObjectName("Explanation")
        self.verticalLayout.addWidget(self.Explanation)
        self.Explanation_2 = QtWidgets.QLabel(self.verticalWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Explanation_2.setFont(font)
        self.Explanation_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Explanation_2.setObjectName("Explanation_2")
        self.verticalLayout.addWidget(self.Explanation_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Welcome.setText(_translate("Dialog", "Добро пожаловать в \n"
"Beauty collection!"))
        self.Explanation.setText(_translate("Dialog", "В этой игре вы составляете свою коллекцию из фотографий случайных людей. \n"
"Из этой коллекции вы можете составлять игровые колоды, с которыми вы будете сражаться против других игроков. \n"
"Чем красивее ваши карты, тем больше у вас шансов на победу, потому что сила вашей карты будет зависеть от того, понравится ли она другим пользователям или нет. \n"
"Ваши карты будут развиваться и эволюционировать. \n"
"Так же вы можете менять непонравившиеся вам карты, а те, что нравятся наделять уникальными возможностями, делая вашу коллекцию сильнее.\n"
"Соберите свою уникальную коллекцию и занимайте первые места в рейтинговых соревнованиях и турнирах.\n"
""))
        self.Explanation_2.setText(_translate("Dialog", "Для перехода в следующее меню закройте это окно"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
