# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'general_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_general_window(object):
    def setupUi(self, general_window):
        general_window.setObjectName("general_window")
        general_window.resize(1128, 894)
        self.centralwidget = QtWidgets.QWidget(general_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(-1, -1, 17, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.exit_qpb = QtWidgets.QPushButton(self.centralwidget)
        self.exit_qpb.setObjectName("exit_qpb")
        self.gridLayout.addWidget(self.exit_qpb, 1, 2, 1, 1)
        self.start_menu_qpb = QtWidgets.QPushButton(self.centralwidget)
        self.start_menu_qpb.setObjectName("start_menu_qpb")
        self.gridLayout.addWidget(self.start_menu_qpb, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.stacked_widget_general = QtWidgets.QStackedWidget(self.centralwidget)
        self.stacked_widget_general.setObjectName("stacked_widget_general")
        self.stacked_widget_global_QVlayout = QtWidgets.QWidget()
        self.stacked_widget_global_QVlayout.setObjectName("stacked_widget_global_QVlayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.stacked_widget_global_QVlayout)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stacked_widget_general.addWidget(self.stacked_widget_global_QVlayout)
        self.gridLayout.addWidget(self.stacked_widget_general, 0, 0, 1, 3)
        general_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(general_window)
        QtCore.QMetaObject.connectSlotsByName(general_window)

    def retranslateUi(self, general_window):
        _translate = QtCore.QCoreApplication.translate
        general_window.setWindowTitle(_translate("general_window", "general_window"))
        self.exit_qpb.setText(_translate("general_window", "Exit"))
        self.start_menu_qpb.setText(_translate("general_window", "Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    general_window = QtWidgets.QMainWindow()
    ui = Ui_general_window()
    ui.setupUi(general_window)
    general_window.show()
    sys.exit(app.exec_())
