# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tutorial_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(722, 666)
        self.verticalWidget = QtWidgets.QWidget(Dialog)
        self.verticalWidget.setGeometry(QtCore.QRect(20, 30, 601, 541))
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Explanation = QtWidgets.QLabel(self.verticalWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Explanation.setFont(font)
        self.Explanation.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.Explanation.setWordWrap(True)
        self.Explanation.setObjectName("Explanation")
        self.verticalLayout.addWidget(self.Explanation)
        self.Explanation_2 = QtWidgets.QLabel(self.verticalWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Explanation_2.setFont(font)
        self.Explanation_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Explanation_2.setObjectName("Explanation_2")
        self.verticalLayout.addWidget(self.Explanation_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Explanation.setText(_translate("Dialog", "Сейчас вы начнёте составлять свою коллекцию. \n"
"\n"
"Вам будут предложены 12 пар карт, из которых вы должны выбрать те, что вам больше нравятся.\n"
" \n"
"Чем красивее ваша коллекция, тем больше у вас шансов на победу в играх. \n"
"\n"
"Вы всегда сможете дополнить свою коллекцию, заменить или удалить непонравившиеся карты, но ваша коллекция не может быть меньше 12-ти карт, помните это когда будете удалять или менять карты.\n"
""))
        self.Explanation_2.setText(_translate("Dialog", "Закройте это окно что бы перейти к составлению коллекции"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
