# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'box.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Box(object):
    def setupUi(self, Box):
        Box.setObjectName("Box")
        Box.resize(1575, 850)
        self.centralwidget = QtWidgets.QWidget(Box)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 1651, 841))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Main_laiout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Main_laiout.setContentsMargins(0, 0, 0, 0)
        self.Main_laiout.setObjectName("Main_laiout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.img_1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_1.sizePolicy().hasHeightForWidth())
        self.img_1.setSizePolicy(sizePolicy)
        self.img_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Buty_frames/Leonardo_DiCaprio_1/GG0000_0.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.img_1.setIcon(icon)
        self.img_1.setIconSize(QtCore.QSize(768, 768))
        self.img_1.setObjectName("img_1")
        self.horizontalLayout.addWidget(self.img_1)
        self.img_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_2.sizePolicy().hasHeightForWidth())
        self.img_2.setSizePolicy(sizePolicy)
        self.img_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Buty_frames/Leonardo_DiCaprio_2/GG0042_0.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.img_2.setIcon(icon1)
        self.img_2.setIconSize(QtCore.QSize(768, 768))
        self.img_2.setObjectName("img_2")
        self.horizontalLayout.addWidget(self.img_2)
        self.Main_laiout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lb_name_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_name_1.sizePolicy().hasHeightForWidth())
        self.lb_name_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lb_name_1.setFont(font)
        self.lb_name_1.setObjectName("lb_name_1")
        self.horizontalLayout_2.addWidget(self.lb_name_1)
        self.lb_name_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_name_2.sizePolicy().hasHeightForWidth())
        self.lb_name_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lb_name_2.setFont(font)
        self.lb_name_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lb_name_2.setTextFormat(QtCore.Qt.PlainText)
        self.lb_name_2.setObjectName("lb_name_2")
        self.horizontalLayout_2.addWidget(self.lb_name_2)
        self.Main_laiout.addLayout(self.horizontalLayout_2)
        Box.setCentralWidget(self.centralwidget)

        self.retranslateUi(Box)
        QtCore.QMetaObject.connectSlotsByName(Box)

    def retranslateUi(self, Box):
        _translate = QtCore.QCoreApplication.translate
        Box.setWindowTitle(_translate("Box", "Box"))
        self.lb_name_1.setText(_translate("Box", "TextLabel"))
        self.lb_name_2.setText(_translate("Box", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Box = QtWidgets.QMainWindow()
    ui = Ui_Box()
    ui.setupUi(Box)
    Box.show()
    sys.exit(app.exec_())
