# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Buty.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1575, 850)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.img_1 = QtWidgets.QPushButton(self.centralwidget)
        self.img_1.setGeometry(QtCore.QRect(10, 10, 768, 768))
        self.img_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Buty_frames/Leonardo_DiCaprio_1/GG0000_0.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.img_1.setIcon(icon)
        self.img_1.setIconSize(QtCore.QSize(768, 768))
        self.img_1.setObjectName("img_1")
        self.img_2 = QtWidgets.QPushButton(self.centralwidget)
        self.img_2.setGeometry(QtCore.QRect(788, 10, 768, 768))
        self.img_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Buty_frames/Leonardo_DiCaprio_2/GG0042_0.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.img_2.setIcon(icon1)
        self.img_2.setIconSize(QtCore.QSize(768, 768))
        self.img_2.setObjectName("img_2")
        self.lb_name_1 = QtWidgets.QLabel(self.centralwidget)
        self.lb_name_1.setGeometry(QtCore.QRect(10, 780, 771, 70))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lb_name_1.setFont(font)
        self.lb_name_1.setObjectName("lb_name_1")
        self.lb_name_2 = QtWidgets.QLabel(self.centralwidget)
        self.lb_name_2.setGeometry(QtCore.QRect(788, 780, 766, 70))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lb_name_2.setFont(font)
        self.lb_name_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lb_name_2.setTextFormat(QtCore.Qt.PlainText)
        self.lb_name_2.setObjectName("lb_name_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lb_name_1.setText(_translate("MainWindow", "TextLabel"))
        self.lb_name_2.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
