# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Global_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Global_menu(object):
    def setupUi(self, Global_menu):
        Global_menu.setObjectName("Global_menu")
        Global_menu.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Global_menu)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 19, 781, 561))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Play = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Play.sizePolicy().hasHeightForWidth())
        self.Play.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.Play.setFont(font)
        self.Play.setObjectName("Play")
        self.horizontalLayout.addWidget(self.Play)
        self.Collection = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Collection.sizePolicy().hasHeightForWidth())
        self.Collection.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.Collection.setFont(font)
        self.Collection.setObjectName("Collection")
        self.horizontalLayout.addWidget(self.Collection)
        Global_menu.setCentralWidget(self.centralwidget)

        self.retranslateUi(Global_menu)
        QtCore.QMetaObject.connectSlotsByName(Global_menu)

    def retranslateUi(self, Global_menu):
        _translate = QtCore.QCoreApplication.translate
        Global_menu.setWindowTitle(_translate("Global_menu", "MainWindow"))
        self.Play.setText(_translate("Global_menu", "Play"))
        self.Collection.setText(_translate("Global_menu", "Collection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Global_menu = QtWidgets.QMainWindow()
    ui = Ui_Global_menu()
    ui.setupUi(Global_menu)
    Global_menu.show()
    sys.exit(app.exec_())
